AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Line Messaging API Webhook Handler using AWS Lambda'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  LineChannelSecret:
    Type: String
    Description: Line Channel Secret
  
  LineChannelAccessToken:
    Type: String
    Description: Line Channel Access Token

  MongoDbConnectionStr:
    Type: String
    Description: MongoDB connection string
    
Resources:
  LineChannelSecretParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pharaoh/${Environment}/line/channel-secret"
      Description: "Line Channel Secret"
      Type: String
      Value: !Ref LineChannelSecret

  LineChannelAccessTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pharaoh/${Environment}/line/channel-access-token"
      Description: "Line Channel Access Token"
      Type: String
      Value: !Ref LineChannelAccessToken

  MongoDbConnectionStrParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pharaoh/${Environment}/mongodb/coonnect-str"
      Description: "MongoDB connection string"
      Type: String
      Value: !Ref MongoDbConnectionStr

  LineWebhookFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "line-webhook-role-${Environment}"
      # REQUIRED
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SsmParameterReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/pharaoh/${Environment}/*"
        - PolicyName: SecretReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/pharaoh/${Environment}/*"

  SyncTwDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.13
      FunctionName: !Sub 'sync-tw-data-${Environment}'
      CodeUri: ../src/
      Handler: sync_tw_data.handler
      Description: 'Scheduled task to sync daily buy/sell data from TWSE/TPEX to MongoDB.'
      MemorySize: 256
      Timeout: 300 # 5 minutes, as fetching data can be slow
      Role: !GetAtt LineWebhookFunctionRole.Arn
      Events:
        ScheduledSync:
          Type: Schedule
          Properties:
            Schedule: 'cron(1 9 ? * MON-FRI *)' # 5:01 PM in Taipei (UTC+8)

  # Lambda Function
  LineWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.13
      FunctionName: !Sub 'line-webhook-${Environment}'
      CodeUri: ../src/
      Handler: app.lambda_handler
      Description: 'Handles Line Messaging API webhook notifications'
      MemorySize: 256
      Timeout: 60
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Role: !GetAtt LineWebhookFunctionRole.Arn
      Events:
        LineWebhookApi:
          Type: Api
          Properties:
            RestApiId: !Ref LineWebhookApi
            Path: /webhook
            Method: post
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LINE_CHANNEL_SECRET: !Ref LineChannelSecret
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
      Tags:
        Environment: !Ref Environment
        Project: pharaoh
        Service: line-webhook

  # API Gateway
  LineWebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'line-webhook-api-${Environment}'
      StageName: !Ref Environment
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-line-signature'"
        AllowOrigin: "'*'"
      Tags:
        Environment: !Ref Environment
        Project: pharaoh
        Service: line-webhook

  # CloudWatch Log Groups
  LineWebhookFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/line-webhook-${Environment}'
      RetentionInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: pharaoh
        - Key: Service
          Value: line-webhook

  # Dead Letter Queue for failed Lambda executions
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'line-webhook-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeout: 60
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: pharaoh
        - Key: Service
          Value: line-webhook

  # CloudWatch Alarms
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'line-webhook-lambda-errors-${Environment}'
      AlarmDescription: 'Lambda function errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LineWebhookFunction
      TreatMissingData: notBreaching

  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'line-webhook-lambda-duration-${Environment}'
      AlarmDescription: 'Lambda function duration'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 25000  # 25 seconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LineWebhookFunction
      TreatMissingData: notBreaching

  ApiGateway4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'line-webhook-api-4xx-${Environment}'
      AlarmDescription: 'API Gateway 4xx errors'
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub 'line-webhook-api-${Environment}'
        - Name: Stage
          Value: !Ref Environment
      TreatMissingData: notBreaching

  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'line-webhook-api-5xx-${Environment}'
      AlarmDescription: 'API Gateway 5xx errors'
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub 'line-webhook-api-${Environment}'
        - Name: Stage
          Value: !Ref Environment
      TreatMissingData: notBreaching

Outputs:
  WebhookUrl:
    Description: 'Line Webhook URL'
    Value: !Sub 'https://${LineWebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/webhook'
    Export:
      Name: !Sub '${AWS::StackName}-webhook-url'

  LambdaFunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt LineWebhookFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-lambda-arn'

  ApiGatewayId:
    Description: 'API Gateway ID'
    Value: !Ref LineWebhookApi
    Export:
      Name: !Sub '${AWS::StackName}-api-id'